# Job Requirements Analysis
Load CSV from CLI output and compute frequency table.

In [1]:
from pathlib import Path

import pandas as pd

csv_path = Path("../data/out/skills.csv")  # adjust if needed
df = pd.read_csv(csv_path)
df.head()

   id                             skill
0  48                            Golang
1  48       Fault-tolerant applications
2  48          Distributed applications
3  48             Adaptive applications
4  48  Manufacturing execution software

# Group by skill

In [2]:
# Group by Skill and count
df["skill"] = df["skill"].str.lower()
df.groupby(["skill"]).size().reset_index(name="count").sort_values(
    by="count", ascending=False
).head(30)

                   skill  count
188               python     17
203                 rust     12
147           kubernetes     10
89                docker     10
141                 java      9
25                   aws      8
184           postgresql      7
229                  sql      6
254           typescript      6
115                  git      6
162        microservices      4
87   distributed systems      4
146               kotlin      4
27                 azure      4
195                react      4
93               english      4
117       github actions      4
82                devops      4
247            terraform      4
72       data structures      3
41                 ci/cd      3
144                kafka      3
142           javascript      3
43       ci/cd pipelines      3
197                redis      3
37                     c      3
8             algorithms      3
39                   c++      3
113               german      3
119                   go      3

# Fix skills

## Fix skills

In [ ]:
df["skill"] = df["skill"].apply(lambda x: "go" if x == "golang" else x)
df["skill"] = df["skill"].apply(lambda x: "postgresql" if x == "postgres" else x)

## Investigate data

In [34]:
sorted([skill for skill in skills if "vs" in skill])

['vs code', 'vs code extension api']

In [31]:
df[df.skill.str.contains("java")]

     id                                              skill   short_skill
34   45                                               java          java
73   11                                               java          java
74   11                                         javascript    javascript
178  32                                               java          java
199  13                                               java          java
201  13                                         javascript    javascript
254  41                                               java          java
256  41                               bouncycastle in java  bouncycastle
278  28                                               java          java
323  10                                               java          java
325  29                                          core java          core
339  29  large scale and highly available rest api's in...         large
358  34                                               java          java
359  34                                         javascript    javascript
399  36                                               java          java

# Group by short skill

Only one word

In [19]:
df["short_skill"] = df["skill"].str.split().str[0]
df.groupby(["short_skill"]).size().reset_index(name="count").sort_values(
    by="count", ascending=False
).head(30)

       short_skill  count
148         python     20
158           rust     13
58          docker     10
111     kubernetes     10
105           java      9
18             aws      9
33           cloud      8
47            data      8
171       software      7
144     postgresql      7
32           ci/cd      7
200     typescript      7
83             git      6
56     distributed      6
176            sql      6
35            code      5
152          react      5
54          devops      5
86              go      5
84          github      5
110         kotlin      4
194      terraform      4
62         english      4
125  microservices      4
4               ai      4
19           azure      4
15      automation      3
81          german      3
108          kafka      3
116          linux      3